/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteRouteImport } from './routes/categories/route'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesCategoryIdRuleIdRouteImport } from './routes/categories/$categoryId/$ruleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRouteRoute = CategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRouteRoute,
} as any)
const CategoriesCategoryIdRuleIdRoute =
  CategoriesCategoryIdRuleIdRouteImport.update({
    id: '/$categoryId/$ruleId',
    path: '/$categoryId/$ruleId',
    getParentRoute: () => CategoriesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/categories/': typeof CategoriesIndexRoute
  '/categories/$categoryId/$ruleId': typeof CategoriesCategoryIdRuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/categories/$categoryId/$ruleId': typeof CategoriesCategoryIdRuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/categories/': typeof CategoriesIndexRoute
  '/categories/$categoryId/$ruleId': typeof CategoriesCategoryIdRuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/categories' | '/categories/' | '/categories/$categoryId/$ruleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories' | '/categories/$categoryId/$ruleId'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/categories/'
    | '/categories/$categoryId/$ruleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRouteRoute: typeof CategoriesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/categories/$categoryId/$ruleId': {
      id: '/categories/$categoryId/$ruleId'
      path: '/$categoryId/$ruleId'
      fullPath: '/categories/$categoryId/$ruleId'
      preLoaderRoute: typeof CategoriesCategoryIdRuleIdRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
  }
}

interface CategoriesRouteRouteChildren {
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CategoriesCategoryIdRuleIdRoute: typeof CategoriesCategoryIdRuleIdRoute
}

const CategoriesRouteRouteChildren: CategoriesRouteRouteChildren = {
  CategoriesIndexRoute: CategoriesIndexRoute,
  CategoriesCategoryIdRuleIdRoute: CategoriesCategoryIdRuleIdRoute,
}

const CategoriesRouteRouteWithChildren = CategoriesRouteRoute._addFileChildren(
  CategoriesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRouteRoute: CategoriesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
